### ISSUE TITLE
Latest version fails to start with: No module named 'audioop'

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#255]
Seems like there is a missing dependency when I try to start the latest version with Python 3.13:

`ModuleNotFoundError: No module named 'audioop'`

Edit: apparently removed in Python 3.13: https://docs.python.org/3/library/audioop.html

**Comment by TrueBrain** [comment]
Dibridge is currently meant to be run on Python 3.10. We currently do not support any other version.

If you want to run it on 3.13 you would have to figure out yourself what dependencies are missing and install them. Most likely installing via `pip install -r requirements.base` would do the trick, but no guarantees. We only test with 3.10 atm.

**Comment by poVoq** [comment]
Seems the module has been depreciated since 3.11 and is removed in 3.13: https://docs.python.org/3/library/audioop.html

I think I ran dibridge with Python3.12 fine before without changes.

**Comment by LordAro** [comment]
This repo contains no references to audioop, so whatever it is must be one of the dependencies. You should probably ask there (wherever that is, as there's no stack trace)
