### ISSUE TITLE
Some issues with puppet username to discord username translations

### ISSUE THREAD

**Issue by glx22** [OpenTTD/dibridge#37]
I noticed at least 2 issues.

Firstly the regex on https://github.com/OpenTTD/dibridge/blob/main/dibridge/irc.py#L144 fails if puppet username contains `[]`
https://discord.com/channels/142724111502802944/1008473233844097104/1010288501742383104
![image](https://user-images.githubusercontent.com/2952192/185987813-ed564eca-4651-4e74-92f4-efb04fa6bf7c.png) vs https://weblogs.openttd.org/openttd/2022/08/19.html#204548-124
```
22:45:48 <glx> my irc client will highlight for both glx and glx[d] (because I used a lazy method) but on discord only the [d] version will trigger
22:46:32 <glx> glx[d]: only this format
``` 
and https://discord.com/channels/142724111502802944/1008473233844097104/1010329543644549200
![image](https://user-images.githubusercontent.com/2952192/185999876-9b1a3a46-9578-4b4d-8c64-2137f7d84f2d.png)
vs https://weblogs.openttd.org/openttd/2022/08/19.html#232854-146
```
01:28:54 <glx> let's try glxd
01:29:04 <glx> and discord notified
```

Secondly, puppet username may be translated when it's unwanted https://discord.com/channels/142724111502802944/1008473233844097104/1011205826792407081
![image](https://user-images.githubusercontent.com/2952192/185988051-352ec2e1-cc71-446c-927c-b834d2629f3b.png) vs https://weblogs.openttd.org/openttd/2022/08/22.html#093056-72
```
11:30:56 <peter1138> https://fuzzle.org/~petern/ottd/diagstations.png
11:30:58 <peter1138> Such old.
11:31:58 <peter1138> https://fuzzle.org/~petern/ottd/stbr3.png
11:31:59 <peter1138> Hehe
```

**Comment by TrueBrain** [comment]
Not sure we want to / should fix the second part. You do want highlights if people to things like `TrueBrain:` or `TrueBrain/glx` .. so where do you draw the line.

Always the balance of: what is worse, too many highlights, or too few. Tricky :)

But if we do want to fix it, I guess we should extend `\w` with `~`, to ignore the highlight in those cases. I would not add `/` to that list, for the above case.

What do you think?

**Comment by frosch123** [comment]
I don't think extending the word-character list helps much here. You can create countless positive cases like "~truebrain-ish people", which should hightlight.

The main issue why this issue is an issue at all, is that it breaks an URL link.
So I think the best solution would be to suppress replacement inside "http\S*" parts.

**Comment by TrueBrain** [comment]
After some talk on Discord, I like the idea of:

split on whitespace, check each part for `://`, and if not, replace usernames. Should cover most cases .. for now :D
