### ISSUE TITLE
--irc-channel adds # automatically, but should not.

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#57]
I tried:

`--irc-channel #examplechannel`

An was surprised that it didn't understand the channel.

`--irc-channel "#examplechannel"`

Works but joins `##examplechannel`

So in the end the working version is `--irc-channel examplechannel`

But the # is part of the channel name and should not be added automatically. Also undocumented ;)

**Comment by frosch123** [comment]
The # is a comment character in shell, so the first version will never work. You have to put # in quotes in shell commands.

**Comment by TrueBrain** [comment]
And that is why I add the `#` for you. Will update the docs to reflect that :)
