### ISSUE TITLE
Running multiple instances of dibridge? User-tag customizaton?

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#59]
@TrueBrain 

> This bridge is not really meant to bridge more than one channel, as it will create new puppets for every channel.

So I was planning to run multiple instances by creating seperate systemd service files with different bot names and channel settings, but the above quote got me wondering about Discord user-names.

In the single instance setup a discord user will just get `Examplename[d] ` and because of the `[d]` it is unlikely to clash with existing IRC user nicks.

But assuming you run two dibridge instances and the same person on Discord joins those two bridged channels... now both dibridge instances will try to create a puppet called `Examplename[d] ` which obviously the IRC server will not allow.

I don't really see an easy solution to this, but as workaround one could maybe allow customizing the `[d]` tag? So that one instance adds `[channel1]` and the other `[channel2]` or so to the name?

**Comment by TrueBrain** [comment]
Maybe try things first :D

The puppets will find a valid name to use, sooner or later. They have 1000000 variations to try, so that will be fine :)

Still not the intended use of this bridge, but nothing is stopping you either :)

**Comment by poVoq** [comment]
Running multiple instances via separate systemd service files seems to work without issues.
