### ISSUE TITLE
option to ignore certain users?

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#62]
Sometimes there is a bot that for example posts link previews on the IRC side, and that is a bit annoying to bridge to Discord.

Maybe you could add a simple ignore option with a list of nicks?

Thanks.

**Comment by TrueBrain** [comment]
Personally, I don't think this feature would be a good idea. By not bridging certain dialog from IRC, you create a disconnect in the conversation, even if it is a bot talking. What if someone replies to the bot by saying his name? On Discord this would be very confusing.
So although I understand the initial impulse to say: that shouldn't be bridged, I think in the long run it would do more harm than good.

That said, I wouldn't be against someone making a Pull Request to add this functionality. But as I don't see the added value to a feature like this, I will not be putting in the effort :) Sorry, but I rather be upfront about these things.

Going to close this ticket, as the issue tracker isn't the best place for feature requests. If you feel up for adding the functionality, go for it! Happy to give pointers etc.
