### ISSUE TITLE
Puppet disconnection issues?

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#70]
While this bridge seems to run stable on low traffic Discord channels, I see a lot of puppet disconnection issues on a more busy channel and subsequent dropping of messages IRC side. Since both the bridge and the IRC server are one the very same machine it can't be network connection issues.

The logs are overflowing with messages like this:
```
Sep 17 09:29:41 hpthin VelorenIRCBridge[106818]: 2022-09-17 09:29:41 INFO     [dibridge.irc_puppet.Sharp[GMT2]] Connecting to IRC from 2001:db8:100::1d90:2a6c:2954 ...
Sep 17 09:29:41 hpthin VelorenIRCBridge[106818]: 2022-09-17 09:29:41 INFO     [dibridge.irc_puppet.Zodurus] Connecting to IRC from 2001:db8:100::f81b:1d76:319e ...
Sep 17 09:29:41 hpthin VelorenIRCBridge[106818]: 2022-09-17 09:29:41 WARNING  [dibridge.irc_puppet.Mati_C8] Disconnected from IRC
Sep 17 09:29:41 hpthin VelorenIRCBridge[106818]: 2022-09-17 09:29:41 WARNING  [dibridge.irc_puppet.tenki] Disconnected from IRC
```

Any suggestion how I can investigate the cause of this further? Restarting the bridge always seems to help for a while.

**Comment by TrueBrain** [comment]
I am curious what the IRCd logs are saying, as it seems the disconnect is initiated from the IRCd side. Did it reach a user-limit based on the IPv6 range?

**Comment by poVoq** [comment]
Good point. Nothing in the IRCd logs, but they are set to only log errors. But I guess the bridge might have run into the DDOS protection system of Ergo. I added the puppet IPv6 range to the exemption list now. Lets see if that fixes it.

**Comment by poVoq** [comment]
Seems to have solved it. Will reopen if it happens again.
